Document the control algorithm from Confluence
lsst-ts/ts_ofc pull request #33
Opened 2021-04-30 12:20 UTC by couger01

2021-04-30 14:56 UTC, teweitsai commented on doc/ca-in-ofc.rst
> +The optical feedback control (OFC) estimates the offset (:math:`\vec{u}`) of degree of freedom (DOF) at time :math:`k+1` based on the wavefront error(:math:`\vec{y}_{k}`) at time :math:`k`.
error (:math:`\vec{y}_{k}`)

2021-04-30 14:58 UTC, teweitsai commented on doc/ca-in-ofc.rst
> +The first step is to evaluate the optical state(:math:`\vec{x}_{k}`) at time :math:`k` in the basis of DOF.
state (:math:`\vec{x}_{k}`)

2021-04-30 15:03 UTC, teweitsai commented on doc/ca-in-ofc.rst
> +This means :math:`textbf{Q} = \textbf{A}^{T}\textbf{C}^{T}\textbf{C}\textbf{A}`.
`textbf{Q}` failed at:
https://ts-ofc.lsst.io/v/PR-33/ca-in-ofc.html

2021-04-30 15:07 UTC, teweitsai commented on doc/ca-in-ofc.rst
> +    &\rightarrow \vec{m}_{x} + \rho^{2}\textbf{H}(\vec{s} - \vec{s}_{0}), \ \ \ \text{for x00}.
We could try to align the  \text{for x0}, \text{for 0}, and \text{for x00} to make them look better on lsst.io.

2021-04-30 15:08 UTC, teweitsai approved these changes
The generated document looks good to me. It looks like the rst support the latex math well (better than the confluence page, which I know `&=` is not supported in my memory. Thanks!

2021-04-30 22:07 UTC, tribeiro requested changes
Can you please move these docs to the developer-guide space?

2021-04-30 22:22 UTC, tribeiro commented on doc/ca-in-ofc.rst
> +Consider three different reference points "x0, "0", and "x00". "x0" means the offset will only trace the previous one; "0" means the offset will trace the real value and target for 0; "x00" means the
Can you break this down into a "definitions list"?

```
Consider three different reference points ``x0``, ``0``, and ``x00``. 

  ``x0``
    The offset will only trace the previous one;
  ``0``
    The offset will trace the real value and target for ``0``
  ``x00``
    The offset will only trace the relative changes of offset without regarding the real value.
```

2021-04-30 22:22 UTC, tribeiro commented on doc/ca-in-ofc.rst
> +The optical state is defined in the following:
in the following ->  as

2021-05-05 14:10 UTC, tribeiro approved these changes
Looks great! Thanks for the updates!

2021-05-05 14:13 UTC, merged